// ═══════════════════════════════════════════════════════════════════
// prebake.c — Build-time asset preprocessor
// ═══════════════════════════════════════════════════════════════════
//
// Runs on the BUILD HOST (x86) during `docker build` to pre-compute
// expensive data that would otherwise be computed at boot on the slow
// ARM device:
//
//   1. SH coefficients — project skybox onto L2 spherical harmonics
//      (27 floats).  Used at runtime for dice IBL lighting.
//      Output: prebaked_sh.inc (C array literal)
//
//   2. Baked floor texture — per-pixel lit hardwood floor combining
//      diffuse, bump, and roughness maps with directional + sky lighting.
//      Output: baked_floor.png
//
// This eliminates ~90% of the "Materials & floor" boot time on device.
//
// Usage: prebake <assets_dir> <output_dir>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// ── Light directions (must match rendering.cpp) ──
static float light_key[3], light_fill[3];

static void vec3_normalize(float* v) {
    float len = sqrtf(v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
    if (len > 1e-6f) { v[0] /= len; v[1] /= len; v[2] /= len; }
}

static void init_lights(void) {
    light_key[0] = 0.4f; light_key[1] = 0.8f; light_key[2] = 0.5f;
    vec3_normalize(light_key);
    light_fill[0] = -0.5f; light_fill[1] = 0.3f; light_fill[2] = -0.3f;
    vec3_normalize(light_fill);
}

// ═══════════════════════════════════════════════════════════════════
// SH projection (same math as rendering.cpp ProjectSkyboxToSH)
// ═══════════════════════════════════════════════════════════════════

static float sh_coeffs[9][3];

static void project_sh(const char* path) {
    int w, h, ch;
    unsigned char* px = stbi_load(path, &w, &h, &ch, 3);
    if (!px) { fprintf(stderr, "prebake: cannot load %s\n", path); return; }

    double acc[9][3] = {};
    double weight_sum = 0;

    for (int y = 0; y < h; y++) {
        float v = ((float)y + 0.5f) / h;
        float theta = v * (float)M_PI;
        float sin_t = sinf(theta), cos_t = cosf(theta);
        float d_omega = sin_t;

        for (int x = 0; x < w; x++) {
            float u = ((float)x + 0.5f) / w;
            float phi = u * 2.0f * (float)M_PI;

            float dx = sin_t * sinf(phi);
            float dy = cos_t;
            float dz = sin_t * cosf(phi);

            int i = (y * w + x) * 3;
            float r = px[i] / 255.0f;
            float g = px[i+1] / 255.0f;
            float b = px[i+2] / 255.0f;

            float basis[9];
            basis[0] = 0.282095f;
            basis[1] = 0.488603f * dy;
            basis[2] = 0.488603f * dz;
            basis[3] = 0.488603f * dx;
            basis[4] = 1.092548f * dx * dy;
            basis[5] = 1.092548f * dy * dz;
            basis[6] = 0.315392f * (3*dy*dy - 1);
            basis[7] = 1.092548f * dx * dz;
            basis[8] = 0.546274f * (dx*dx - dz*dz);

            for (int k = 0; k < 9; k++) {
                acc[k][0] += r * basis[k] * d_omega;
                acc[k][1] += g * basis[k] * d_omega;
                acc[k][2] += b * basis[k] * d_omega;
            }
            weight_sum += d_omega;
        }
    }

    float scale = (4.0f * (float)M_PI) / (float)weight_sum;
    for (int k = 0; k < 9; k++) {
        sh_coeffs[k][0] = (float)(acc[k][0] * scale);
        sh_coeffs[k][1] = (float)(acc[k][1] * scale);
        sh_coeffs[k][2] = (float)(acc[k][2] * scale);
    }

    stbi_image_free(px);
    fprintf(stderr, "prebake: SH projected from %s (%dx%d)\n", path, w, h);
}

static int write_sh_inc(const char* path) {
    FILE* f = fopen(path, "w");
    if (!f) { fprintf(stderr, "prebake: cannot write %s\n", path); return -1; }

    fprintf(f, "// Auto-generated by tools/prebake.c — do not edit\n");
    fprintf(f, "// L2 spherical harmonic coefficients from skybox\n");
    fprintf(f, "static float shCoeffs[9][3] = {\n");
    for (int k = 0; k < 9; k++) {
        fprintf(f, "    {%+.8ef, %+.8ef, %+.8ef},\n",
                sh_coeffs[k][0], sh_coeffs[k][1], sh_coeffs[k][2]);
    }
    fprintf(f, "};\n");
    fprintf(f, "static bool shReady = true;\n");

    fclose(f);
    fprintf(stderr, "prebake: wrote %s\n", path);
    return 0;
}

// ═══════════════════════════════════════════════════════════════════
// Sky probes (same math as rendering.cpp BuildSkyProbes)
// ═══════════════════════════════════════════════════════════════════

#define NUM_SKY_PROBES 6
struct SkyProbe { float dir[3]; float r, g, b; };
static struct SkyProbe sky_probes[NUM_SKY_PROBES];
static int num_sky_probes = 0;

static void build_sky_probes(const char* path) {
    int w, h, ch;
    unsigned char* px = stbi_load(path, &w, &h, &ch, 3);
    if (!px) return;

    const int COLS = 6, ROWS = 3;
    int idx = 0;
    for (int gy = 0; gy < ROWS && idx < NUM_SKY_PROBES; gy++) {
        float best_lum[2] = {0, 0};
        int best_col[2] = {0, 1};
        for (int gx = 0; gx < COLS; gx++) {
            float sumR = 0, sumG = 0, sumB = 0;
            int count = 0;
            int x0 = gx * w / COLS, x1 = (gx + 1) * w / COLS;
            int y0 = gy * h / ROWS, y1 = (gy + 1) * h / ROWS;
            for (int yy = y0; yy < y1; yy++)
                for (int xx = x0; xx < x1; xx++) {
                    int i = (yy * w + xx) * 3;
                    sumR += px[i]; sumG += px[i+1]; sumB += px[i+2];
                    count++;
                }
            float lum = (sumR * 0.299f + sumG * 0.587f + sumB * 0.114f) / count;
            for (int k = 0; k < 2; k++) {
                if (lum > best_lum[k]) {
                    if (k == 0) { best_lum[1] = best_lum[0]; best_col[1] = best_col[0]; }
                    best_lum[k] = lum; best_col[k] = gx;
                    break;
                }
            }
        }
        for (int k = 0; k < 2 && idx < NUM_SKY_PROBES; k++) {
            int gx = best_col[k];
            float u = ((float)gx + 0.5f) / COLS;
            float v = ((float)gy + 0.5f) / ROWS;
            float azimuth = u * 2.0f * (float)M_PI;
            float elevation = (0.5f - v) * (float)M_PI;
            float dir[3] = {
                cosf(elevation) * sinf(azimuth),
                sinf(elevation),
                cosf(elevation) * cosf(azimuth),
            };
            vec3_normalize(dir);

            int x0 = gx * w / COLS, x1 = (gx + 1) * w / COLS;
            int y0 = gy * h / ROWS, y1 = (gy + 1) * h / ROWS;
            float sumR = 0, sumG = 0, sumB = 0;
            int count = 0;
            for (int yy = y0; yy < y1; yy++)
                for (int xx = x0; xx < x1; xx++) {
                    int i = (yy * w + xx) * 3;
                    sumR += px[i]; sumG += px[i+1]; sumB += px[i+2];
                    count++;
                }
            sky_probes[idx].dir[0] = dir[0];
            sky_probes[idx].dir[1] = dir[1];
            sky_probes[idx].dir[2] = dir[2];
            sky_probes[idx].r = (sumR / count) / 255.0f;
            sky_probes[idx].g = (sumG / count) / 255.0f;
            sky_probes[idx].b = (sumB / count) / 255.0f;
            idx++;
        }
    }
    stbi_image_free(px);
    num_sky_probes = idx;
    fprintf(stderr, "prebake: built %d sky probes\n", idx);
}

// ═══════════════════════════════════════════════════════════════════
// Floor bake (same math as rendering.cpp BakeLitFloorTexture)
// ═══════════════════════════════════════════════════════════════════

static float sample_gray(const unsigned char* data, int w, int h, float u, float v) {
    if (!data) return 0.5f;
    u = u - floorf(u); v = v - floorf(v);
    int px = (int)(u * w) % w;
    int py = (int)(v * h) % h;
    if (px < 0) px += w;
    if (py < 0) py += h;
    return data[py * w + px] / 255.0f;
}

static void bump_normal(const unsigned char* bump_data, int bw, int bh,
                        float bump_lo, float bump_range,
                        float u, float v, float texel_size,
                        float* out_n) {
    float hc = (sample_gray(bump_data, bw, bh, u, v)              - bump_lo) / bump_range;
    float hx = (sample_gray(bump_data, bw, bh, u + texel_size, v) - bump_lo) / bump_range;
    float hy = (sample_gray(bump_data, bw, bh, u, v + texel_size) - bump_lo) / bump_range;
    float scale = 2.5f;
    out_n[0] = -(hx - hc) * scale;
    out_n[1] = 1.0f;
    out_n[2] = -(hy - hc) * scale;
    vec3_normalize(out_n);
}

static float dot3(const float* a, const float* b) {
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2];
}

static int bake_floor(const char* diffuse_path, const char* bump_path,
                      const char* rough_path, const char* out_path) {
    int dw, dh, dch;
    unsigned char* diff_px = stbi_load(diffuse_path, &dw, &dh, &dch, 3);
    if (!diff_px) {
        fprintf(stderr, "prebake: cannot load %s, generating fallback\n", diffuse_path);
        dw = 64; dh = 64;
        diff_px = (unsigned char*)malloc(dw * dh * 3);
        for (int i = 0; i < dw * dh; i++) {
            diff_px[i*3] = 140; diff_px[i*3+1] = 100; diff_px[i*3+2] = 58;
        }
    }

    int bw = 0, bh = 0;
    unsigned char* bump_px = NULL;
    if (bump_path) {
        int bch;
        bump_px = stbi_load(bump_path, &bw, &bh, &bch, 1);
    }

    int rw = 0, rh = 0;
    unsigned char* rough_px = NULL;
    if (rough_path) {
        int rch;
        rough_px = stbi_load(rough_path, &rw, &rh, &rch, 1);
    }

    // Normalize bump range
    float bump_lo = 1.0f, bump_hi = 0.0f;
    if (bump_px) {
        for (int i = 0; i < bw * bh; i++) {
            float v = bump_px[i] / 255.0f;
            if (v < bump_lo) bump_lo = v;
            if (v > bump_hi) bump_hi = v;
        }
    }
    float bump_range = (bump_hi > bump_lo) ? (bump_hi - bump_lo) : 1.0f;

    float texel_size = 1.0f / dw;
    float view_dir[3] = {0.0f, 1.0f, 0.3f};
    vec3_normalize(view_dir);

    unsigned char* out = (unsigned char*)malloc(dw * dh * 4);

    for (int py = 0; py < dh; py++) {
        float v = (py + 0.5f) / dh;
        for (int px = 0; px < dw; px++) {
            float u = (px + 0.5f) / dw;

            int di = (py * dw + px) * 3;
            float dr = diff_px[di] / 255.0f;
            float dg = diff_px[di+1] / 255.0f;
            float db = diff_px[di+2] / 255.0f;

            float n[3] = {0, 1, 0};
            if (bump_px)
                bump_normal(bump_px, bw, bh, bump_lo, bump_range, u, v, texel_size, n);

            float roughness = 0.7f;
            if (rough_px)
                roughness = sample_gray(rough_px, rw, rh, u, v);
            float glossiness = 1.0f - roughness;

            // Diffuse lighting
            float ambient = 0.25f;
            float key_dot = dot3(n, light_key);
            if (key_dot < 0) key_dot = 0;
            float fill_dot = dot3(n, light_fill);
            if (fill_dot < 0) fill_dot = 0;
            float lr = ambient + 0.50f * key_dot + 0.15f * fill_dot;
            float lg = lr, lb = lr;

            // Specular (Blinn-Phong)
            float half_vec[3] = {
                light_key[0] + view_dir[0],
                light_key[1] + view_dir[1],
                light_key[2] + view_dir[2]
            };
            vec3_normalize(half_vec);
            float spec_dot = dot3(n, half_vec);
            if (spec_dot < 0) spec_dot = 0;
            float spec_pow = 8.0f + glossiness * 48.0f;
            float spec = powf(spec_dot, spec_pow) * glossiness * 0.6f;

            // Sky probe irradiance + specular
            for (int p = 0; p < num_sky_probes; p++) {
                float d = dot3(n, sky_probes[p].dir);
                if (d < 0) d = 0;
                float w = d * 0.25f;
                lr += sky_probes[p].r * w;
                lg += sky_probes[p].g * w;
                lb += sky_probes[p].b * w;

                float hv[3] = {
                    sky_probes[p].dir[0] + view_dir[0],
                    sky_probes[p].dir[1] + view_dir[1],
                    sky_probes[p].dir[2] + view_dir[2]
                };
                vec3_normalize(hv);
                float sd = dot3(n, hv);
                if (sd > 0) {
                    float ps = powf(sd, spec_pow) * glossiness * 0.15f;
                    float lum = sky_probes[p].r * 0.3f + sky_probes[p].g * 0.6f + sky_probes[p].b * 0.1f;
                    spec += ps * lum;
                }
            }

            float fr = dr * lr + spec;
            float fg = dg * lg + spec;
            float fb = db * lb + spec;
            if (fr > 1.0f) fr = 1.0f;
            if (fg > 1.0f) fg = 1.0f;
            if (fb > 1.0f) fb = 1.0f;

            int oi = (py * dw + px) * 4;
            out[oi]   = (unsigned char)(fr * 255);
            out[oi+1] = (unsigned char)(fg * 255);
            out[oi+2] = (unsigned char)(fb * 255);
            out[oi+3] = 255;
        }
    }

    stbi_write_png(out_path, dw, dh, 4, out, dw * 4);
    fprintf(stderr, "prebake: wrote %s (%dx%d)\n", out_path, dw, dh);

    free(out);
    stbi_image_free(diff_px);
    if (bump_px) stbi_image_free(bump_px);
    if (rough_px) stbi_image_free(rough_px);
    return 0;
}

// ═══════════════════════════════════════════════════════════════════

int main(int argc, char** argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: prebake <assets_dir> <output_dir>\n");
        return 1;
    }

    const char* assets = argv[1];
    const char* output = argv[2];
    char path[512];

    init_lights();

    // 1. SH coefficients from skybox
    snprintf(path, sizeof(path), "%s/skybox.png", assets);
    project_sh(path);

    snprintf(path, sizeof(path), "%s/prebaked_sh.inc", output);
    if (write_sh_inc(path) != 0) return 1;

    // 2. Sky probes (needed for floor bake)
    snprintf(path, sizeof(path), "%s/skybox.png", assets);
    build_sky_probes(path);

    // 3. Baked floor texture
    char diff_path[512], bump_path[512], rough_path[512], out_floor[512];
    snprintf(diff_path, sizeof(diff_path), "%s/hardwood2_diffuse.png", assets);
    snprintf(bump_path, sizeof(bump_path), "%s/hardwood2_bump.png", assets);
    snprintf(rough_path, sizeof(rough_path), "%s/hardwood2_roughness.png", assets);
    snprintf(out_floor, sizeof(out_floor), "%s/baked_floor.png", output);
    bake_floor(diff_path, bump_path, rough_path, out_floor);

    fprintf(stderr, "prebake: all done\n");
    return 0;
}
